apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
  labels:
    app: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
      - name: quotes
        image: suyash01/quotes:latest
        ports:
        - containerPort: 8080
        env:
        - name: spring.datasource.url
          value: "jdbc:postgresql://34.27.180.125:5432/mydatabase"
        - name: spring.datasource.username
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD